package bitManipulation;
/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
public class FindtheDifference_389 {
    
    public char findTheDifference(String s, String t) {
        char mask=0;        
        for (char c: s.toCharArray()) mask^=c;
        for (char c: t.toCharArray()) mask^=c;
        return mask;
    }

}
